// Code generated by oto; DO NOT EDIT.

'use strict';

 
export class TodosService {
	
	async all(allRequest) {
		const headers = {
			'Accept':		'application/json',
			'Accept-Encoding':	'gzip',
			'Content-Type':		'application/json',
		}
		allRequest = allRequest || {}
		const response = await fetch('/oto/TodosService.All', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(allRequest)
		})
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error)
			}
			return json
		})
	}
	
	async create(createRequest) {
		const headers = {
			'Accept':		'application/json',
			'Accept-Encoding':	'gzip',
			'Content-Type':		'application/json',
		}
		createRequest = createRequest || {}
		const response = await fetch('/oto/TodosService.Create', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(createRequest)
		})
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error)
			}
			return json
		})
	}
	
}

